apiVersion: v1
kind: Secret
metadata:
  name: ddag-secrets
  namespace: {{ include "ddag.namespace" . }}
  labels:
    {{- include "ddag.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
