//go:build integration

package connectors

import (
	"context"
	"fmt"
	"os"
	"testing"
	"time"
)

func TestOracleConnectorIntegration(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
	defer cancel()
	explicit := oracleIntegrationExplicit()

	cfg := PoolConfig{
		ConnectionID:   "integration-oracle",
		DatabaseType:   "oracle",
		Host:           envOr("DDAG_INTEGRATION_ORACLE_HOST", "127.0.0.1"),
		Port:           envInt("DDAG_INTEGRATION_ORACLE_PORT", 1521),
		ServiceName:    envOr("DDAG_INTEGRATION_ORACLE_SERVICE", "XEPDB1"),
		Username:       envOr("DDAG_INTEGRATION_ORACLE_USER", "ddag_test"),
		Password:       envOr("DDAG_INTEGRATION_ORACLE_PASSWORD", ""),
		MinPool:        0,
		MaxPool:        2,
		ConnectTimeout: 10 * time.Second,
		QueryTimeout:   10 * time.Second,
	}

	if cfg.Password == "" && !explicit {
		t.Skip("skipping Oracle integration test; DDAG_INTEGRATION_ORACLE_PASSWORD not set")
	}

	conn, err := BuildOracle(ctx, cfg)
	if err != nil {
		if explicit {
			t.Fatalf("oracle integration target unavailable at %s:%d/%s: %v", cfg.Host, cfg.Port, cfg.ServiceName, err)
		}
		t.Skipf("oracle integration target unavailable: %v", err)
	}
	defer conn.Close()

	// Clean up old table if exists
	_, _ = conn.Query(ctx, QueryRequest{
		QueryTemplate: "BEGIN EXECUTE IMMEDIATE 'DROP TABLE ddag_int_users'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;",
	})

	// Create table
	_, err = conn.Query(ctx, QueryRequest{
		QueryTemplate: `CREATE TABLE ddag_int_users (
			id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			username VARCHAR2(50) NOT NULL,
			score NUMBER(10,2) NOT NULL,
			is_active NUMBER(1) NOT NULL
		)`,
	})
	if err != nil {
		t.Fatalf("setup create table: %v", err)
	}
	defer func() {
		_, _ = conn.Query(context.Background(), QueryRequest{QueryTemplate: "DROP TABLE ddag_int_users"})
	}()

	// Insert data
	for _, u := range []struct{ name string; score float64; active int }{
		{"alice", 95.50, 1},
		{"bob", 72.00, 0},
		{"charlie", 88.25, 1},
		{"diana", 91.00, 1},
		{"eve", 60.50, 0},
	} {
		_, err = conn.Query(ctx, QueryRequest{
			QueryTemplate: "INSERT INTO ddag_int_users (username, score, is_active) VALUES (:name, :score, :active)",
			Parameters:    map[string]any{"name": u.name, "score": u.score, "active": u.active},
		})
		if err != nil {
			t.Fatalf("setup insert %s: %v", u.name, err)
		}
	}

	// Test 1: Basic read with q-quote string bypassing
	res, err := conn.Query(ctx, QueryRequest{
		QueryTemplate: "SELECT id, username, score FROM ddag_int_users WHERE is_active = :active AND username != q'[fake:param]' ORDER BY id ASC",
		Parameters:    map[string]any{"active": 1},
	})
	if err != nil {
		t.Fatalf("query active users: %v", err)
	}
	if !res.Success || res.RowCount != 3 {
		t.Fatalf("expected 3 active users, got count=%d, res=%+v", res.RowCount, res)
	}
	if fmt.Sprint(res.Rows[0]["USERNAME"]) != "alice" {
		t.Errorf("expected first user 'alice', got %v", res.Rows[0]["USERNAME"])
	}

	// Test 2: Pagination (OFFSET ... FETCH NEXT ... ROWS ONLY)
	res2, err := conn.Query(ctx, QueryRequest{
		QueryTemplate: "SELECT id, username FROM ddag_int_users ORDER BY id ASC",
		Parameters:    map[string]any{},
		Limit:         2,
		Offset:        1,
	})
	if err != nil {
		t.Fatalf("query with pagination: %v", err)
	}
	if !res2.Success || res2.RowCount != 2 {
		t.Fatalf("expected 2 rows after pagination, got %d", res2.RowCount)
	}
	if fmt.Sprint(res2.Rows[0]["USERNAME"]) != "bob" {
		t.Errorf("expected first paginated row 'bob' (offset=1), got %v", res2.Rows[0]["USERNAME"])
	}
	if fmt.Sprint(res2.Rows[1]["USERNAME"]) != "charlie" {
		t.Errorf("expected second paginated row 'charlie', got %v", res2.Rows[1]["USERNAME"])
	}
}

func oracleIntegrationExplicit() bool {
	keys := []string{
		"DDAG_INTEGRATION_ORACLE_HOST",
		"DDAG_INTEGRATION_ORACLE_PORT",
		"DDAG_INTEGRATION_ORACLE_SERVICE",
		"DDAG_INTEGRATION_ORACLE_USER",
		"DDAG_INTEGRATION_ORACLE_PASSWORD",
	}
	for _, key := range keys {
		if _, ok := os.LookupEnv(key); ok {
			return true
		}
	}
	return false
}