// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: api/connector/v1/connector.proto

package connectorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ConnectionId   string                 `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	QueryTemplate  string                 `protobuf:"bytes,3,opt,name=query_template,json=queryTemplate,proto3" json:"query_template,omitempty"`
	ParametersJson []byte                 `protobuf:"bytes,4,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"`
	TimeoutMs      int32                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Limit          int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                  `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_api_connector_v1_connector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_connector_v1_connector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_api_connector_v1_connector_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *QueryRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *QueryRequest) GetQueryTemplate() string {
	if x != nil {
		return x.QueryTemplate
	}
	return ""
}

func (x *QueryRequest) GetParametersJson() []byte {
	if x != nil {
		return x.ParametersJson
	}
	return nil
}

func (x *QueryRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DurationMs    int64                  `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	RowCount      int32                  `protobuf:"varint,3,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	CircuitState  string                 `protobuf:"bytes,4,opt,name=circuit_state,json=circuitState,proto3" json:"circuit_state,omitempty"`
	RowsJson      []byte                 `protobuf:"bytes,5,opt,name=rows_json,json=rowsJson,proto3" json:"rows_json,omitempty"`
	Error         *ErrorDetail           `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_api_connector_v1_connector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_connector_v1_connector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_api_connector_v1_connector_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *QueryResponse) GetRowCount() int32 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *QueryResponse) GetCircuitState() string {
	if x != nil {
		return x.CircuitState
	}
	return ""
}

func (x *QueryResponse) GetRowsJson() []byte {
	if x != nil {
		return x.RowsJson
	}
	return nil
}

func (x *QueryResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_api_connector_v1_connector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_connector_v1_connector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_api_connector_v1_connector_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_connector_v1_connector_proto protoreflect.FileDescriptor

const file_api_connector_v1_connector_proto_rawDesc = "" +
	"\n" +
	" api/connector/v1/connector.proto\x12\x11ddag.connector.v1\"\xef\x01\n" +
	"\fQueryRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\x12%\n" +
	"\x0equery_template\x18\x03 \x01(\tR\rqueryTemplate\x12'\n" +
	"\x0fparameters_json\x18\x04 \x01(\fR\x0eparametersJson\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x05R\ttimeoutMs\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\a \x01(\x05R\x06offset\"\xdf\x01\n" +
	"\rQueryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x03R\n" +
	"durationMs\x12\x1b\n" +
	"\trow_count\x18\x03 \x01(\x05R\browCount\x12#\n" +
	"\rcircuit_state\x18\x04 \x01(\tR\fcircuitState\x12\x1b\n" +
	"\trows_json\x18\x05 \x01(\fR\browsJson\x124\n" +
	"\x05error\x18\x06 \x01(\v2\x1e.ddag.connector.v1.ErrorDetailR\x05error\";\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2^\n" +
	"\x10ConnectorService\x12J\n" +
	"\x05Query\x12\x1f.ddag.connector.v1.QueryRequest\x1a .ddag.connector.v1.QueryResponseB3Z1github.com/ddag/ddag/api/connector/v1;connectorv1b\x06proto3"

var (
	file_api_connector_v1_connector_proto_rawDescOnce sync.Once
	file_api_connector_v1_connector_proto_rawDescData []byte
)

func file_api_connector_v1_connector_proto_rawDescGZIP() []byte {
	file_api_connector_v1_connector_proto_rawDescOnce.Do(func() {
		file_api_connector_v1_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_connector_v1_connector_proto_rawDesc), len(file_api_connector_v1_connector_proto_rawDesc)))
	})
	return file_api_connector_v1_connector_proto_rawDescData
}

var file_api_connector_v1_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_connector_v1_connector_proto_goTypes = []any{
	(*QueryRequest)(nil),  // 0: ddag.connector.v1.QueryRequest
	(*QueryResponse)(nil), // 1: ddag.connector.v1.QueryResponse
	(*ErrorDetail)(nil),   // 2: ddag.connector.v1.ErrorDetail
}
var file_api_connector_v1_connector_proto_depIdxs = []int32{
	2, // 0: ddag.connector.v1.QueryResponse.error:type_name -> ddag.connector.v1.ErrorDetail
	0, // 1: ddag.connector.v1.ConnectorService.Query:input_type -> ddag.connector.v1.QueryRequest
	1, // 2: ddag.connector.v1.ConnectorService.Query:output_type -> ddag.connector.v1.QueryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_connector_v1_connector_proto_init() }
func file_api_connector_v1_connector_proto_init() {
	if File_api_connector_v1_connector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_connector_v1_connector_proto_rawDesc), len(file_api_connector_v1_connector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_connector_v1_connector_proto_goTypes,
		DependencyIndexes: file_api_connector_v1_connector_proto_depIdxs,
		MessageInfos:      file_api_connector_v1_connector_proto_msgTypes,
	}.Build()
	File_api_connector_v1_connector_proto = out.File
	file_api_connector_v1_connector_proto_goTypes = nil
	file_api_connector_v1_connector_proto_depIdxs = nil
}
