#!/usr/bin/env bash
# DDAG's one-command local launcher. Creates an ignored local .env with fresh
# secrets, builds the stack, and prints the dashboard sign-in details.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/.env"
COMPOSE=(docker compose --project-directory "$ROOT")

banner() {
  cat <<'EOF'

  ██████╗ ██████╗  █████╗  ██████╗
  ██╔══██╗██╔══██╗██╔══██╗██╔════╝
  ██║  ██║██║  ██║███████║██║  ███╗
  ██║  ██║██║  ██║██╔══██║██║   ██║
  ██████╔╝██████╔╝██║  ██║╚██████╔╝
  ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝
      Dynamic Database API Gateway

EOF
}

usage() {
  cat <<'EOF'
Usage: ./scripts/quickstart.sh [start|stop|status|logs|reset]

  start   Create local configuration if needed, build, and start DDAG (default)
  stop    Stop containers while preserving data
  status  Show stack status
  logs    Follow Caddy, gateway, and admin logs
  reset   Stop the stack and delete local Postgres/Redis volumes
EOF
}

require() {
  command -v docker >/dev/null 2>&1 || { echo "Error: Docker is required. Install Docker Engine/Desktop and retry." >&2; exit 1; }
  docker compose version >/dev/null 2>&1 || { echo "Error: Docker Compose v2 is required (docker compose ...)." >&2; exit 1; }
  docker info >/dev/null 2>&1 || { echo "Error: Docker is installed but its daemon is not running or accessible." >&2; exit 1; }
}

secret_b64() {
  if command -v openssl >/dev/null 2>&1; then openssl rand -base64 32 | tr -d '\n'
  else python3 -c 'import base64,secrets; print(base64.b64encode(secrets.token_bytes(32)).decode())'; fi
}
secret_hex() {
  if command -v openssl >/dev/null 2>&1; then openssl rand -hex 24
  else python3 -c 'import secrets; print(secrets.token_hex(24))'; fi
}

create_env() {
  [[ -e "$ENV_FILE" ]] && return
  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/quickstart.sh for local development. Never use in production.
DDAG_ENV=local
DDAG_DB_USER=ddag
DDAG_DB_PASSWORD=$(secret_hex)
DDAG_DB_NAME=ddag
DDAG_MASTER_KEY=$(secret_b64)
DDAG_SESSION_SECRET=$(secret_hex)
DDAG_SUPERADMIN_PASSWORD=$(secret_hex)
DDAG_TOKEN_ISSUER=http://localhost
DDAG_DASHBOARD_ORIGINS=http://localhost
DDAG_HTTP_PORT=80
EOF
  chmod 600 "$ENV_FILE"
  echo "Created .env with generated local-only credentials."
}

start() {
  banner
  create_env
  "${COMPOSE[@]}" up --build --detach --wait
  local password
  password="$(awk -F= '/^DDAG_SUPERADMIN_PASSWORD=/{print $2}' "$ENV_FILE")"
  cat <<EOF

  DDAG is ready.
  ├─ Dashboard:  http://localhost
  ├─ Gateway:    http://localhost/api/v1/...
  ├─ Health:     http://localhost/healthz
  └─ Sign in:    superadmin / $password

  Run ./scripts/quickstart.sh logs for live logs.
  Run ./scripts/quickstart.sh stop to stop (data is preserved).
EOF
}

main() {
  case "${1:-start}" in
    start) require; start ;;
    stop) require; "${COMPOSE[@]}" stop ;;
    status) require; "${COMPOSE[@]}" ps ;;
    logs) require; "${COMPOSE[@]}" logs -f caddy api-gateway admin-backend ;;
    reset) require; "${COMPOSE[@]}" down --volumes --remove-orphans; echo "DDAG local data removed." ;;
    -h|--help|help) usage ;;
    *) usage >&2; exit 2 ;;
  esac
}
main "$@"
